name: Trigger auto deployment for scimsession

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/scimsession-AutoDeployTrigger-9dddf565-4a26-4170-92ba-adab31b9e935.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCIMSESSION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCIMSESSION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCIMSESSION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: opscim.azurecr.io
          registryUsername: ${{ secrets.SCIMSESSION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCIMSESSION_REGISTRY_PASSWORD }}
          containerAppName: scimsession
          resourceGroup: 1PASSWORD
          imageToBuild: opscim.azurecr.io/scimsession:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


